2018-06-25 15:18:48,530 [Thread-1    ] [INFO ] [django.server       ]  "GET / HTTP/1.1" 200 5048
2018-06-25 15:18:48,584 [Thread-5    ] [INFO ] [django.server       ]  "GET /static/rest_framework/css/prettify.css HTTP/1.1" 200 817
2018-06-25 15:18:48,597 [Thread-8    ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 200 3597
2018-06-25 15:18:48,599 [Thread-9    ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/csrf.js HTTP/1.1" 200 1735
2018-06-25 15:18:48,605 [Thread-4    ] [INFO ] [django.server       ]  "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 200 3385
2018-06-25 15:18:48,605 [Thread-7    ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/jquery-3.3.1.min.js HTTP/1.1" 200 86927
2018-06-25 15:18:48,606 [Thread-6    ] [INFO ] [django.server       ]  "GET /static/rest_framework/css/default.css HTTP/1.1" 200 1131
2018-06-25 15:18:48,636 [Thread-11   ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/default.js HTTP/1.1" 200 1262
2018-06-25 15:18:48,637 [Thread-10   ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 200 37045
2018-06-25 15:18:48,639 [Thread-3    ] [INFO ] [django.server       ]  "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 200 121200
2018-06-25 15:18:48,663 [Thread-12   ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 200 13632
2018-06-25 15:18:48,886 [Thread-13   ] [INFO ] [django.server       ]  "GET /static/rest_framework/img/grid.png HTTP/1.1" 200 1458
2018-06-25 15:18:49,221 [Thread-14   ] [WARNI] [django.request      ]  Not Found: /favicon.ico
2018-06-25 15:18:49,222 [Thread-14   ] [WARNI] [django.server       ]  "GET /favicon.ico HTTP/1.1" 404 2341
2018-06-25 15:25:26,935 [Thread-1    ] [INFO ] [django.server       ]  "GET / HTTP/1.1" 200 5174
2018-06-25 15:25:28,790 [Thread-3    ] [INFO ] [django.server       ]  "GET /player/ HTTP/1.1" 200 9152
2018-06-25 15:26:37,863 [Thread-4    ] [INFO ] [django.server       ]  "POST /player/ HTTP/1.1" 201 9481
2018-06-25 15:26:37,937 [Thread-6    ] [INFO ] [django.server       ]  "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 304 0
2018-06-25 15:26:37,939 [Thread-7    ] [INFO ] [django.server       ]  "GET /static/rest_framework/css/prettify.css HTTP/1.1" 304 0
2018-06-25 15:26:37,939 [Thread-5    ] [INFO ] [django.server       ]  "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 304 0
2018-06-25 15:26:37,939 [Thread-8    ] [INFO ] [django.server       ]  "GET /static/rest_framework/css/default.css HTTP/1.1" 304 0
2018-06-25 15:26:37,940 [Thread-9    ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/jquery-3.3.1.min.js HTTP/1.1" 304 0
2018-06-25 15:26:37,942 [Thread-10   ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
2018-06-25 15:26:37,943 [Thread-11   ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
2018-06-25 15:26:37,966 [Thread-12   ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
2018-06-25 15:26:37,969 [Thread-14   ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
2018-06-25 15:26:37,969 [Thread-13   ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
2018-06-25 15:26:38,008 [Thread-15   ] [INFO ] [django.server       ]  "GET /static/rest_framework/img/grid.png HTTP/1.1" 304 0
2018-06-25 15:26:39,399 [Thread-16   ] [WARNI] [django.request      ]  Not Found: /media/download.jpg
2018-06-25 15:26:39,400 [Thread-16   ] [WARNI] [django.server       ]  "GET /media/download.jpg HTTP/1.1" 404 3176
2018-06-25 15:27:15,334 [Thread-1    ] [INFO ] [django.server       ]  "GET /player/ HTTP/1.1" 200 9457
2018-06-25 15:27:16,898 [Thread-3    ] [INFO ] [django.server       ]  "GET /media/download.jpg HTTP/1.1" 200 7572
2018-06-25 15:27:57,393 [Thread-8    ] [INFO ] [django.server       ]  "POST /player/ HTTP/1.1" 201 9489
2018-06-25 15:28:00,434 [Thread-9    ] [INFO ] [django.server       ]  "GET /player/ HTTP/1.1" 200 9767
2018-06-25 15:28:39,468 [Thread-15   ] [INFO ] [django.server       ]  "POST /player/ HTTP/1.1" 201 9499
2018-06-25 15:29:07,090 [Thread-16   ] [INFO ] [django.server       ]  "POST /player/ HTTP/1.1" 201 9499
2018-06-25 15:29:09,214 [Thread-17   ] [INFO ] [django.server       ]  "GET /player/ HTTP/1.1" 200 10397
2018-06-25 15:29:48,413 [Thread-23   ] [INFO ] [django.server       ]  "POST /player/ HTTP/1.1" 201 9509
2018-06-25 15:29:50,875 [Thread-24   ] [INFO ] [django.server       ]  "GET /player/ HTTP/1.1" 200 10717
2018-06-25 15:29:52,790 [Thread-25   ] [INFO ] [django.server       ]  "GET / HTTP/1.1" 200 5174
2018-06-25 15:29:54,171 [Thread-26   ] [INFO ] [django.server       ]  "GET /player/ HTTP/1.1" 200 10717
2018-06-25 15:30:19,940 [Thread-31   ] [INFO ] [django.server       ]  "GET /media/download-3.jpg HTTP/1.1" 200 4405
2018-06-25 15:33:59,494 [Thread-1    ] [ERROR] [django.request      ]  Internal Server Error: /get_players
Traceback (most recent call last):
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/decorators.py", line 43, in decorator
    '@api_view missing list of allowed HTTP methods'
AssertionError: @api_view missing list of allowed HTTP methods
2018-06-25 15:33:59,627 [Thread-1    ] [ERROR] [django.server       ]  "GET /get_players HTTP/1.1" 500 64337
2018-06-25 15:34:03,503 [Thread-3    ] [ERROR] [django.request      ]  Internal Server Error: /get_players/
Traceback (most recent call last):
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/decorators.py", line 43, in decorator
    '@api_view missing list of allowed HTTP methods'
AssertionError: @api_view missing list of allowed HTTP methods
2018-06-25 15:34:03,536 [Thread-3    ] [ERROR] [django.server       ]  "GET /get_players/ HTTP/1.1" 500 64348
2018-06-25 15:34:16,648 [Thread-1    ] [INFO ] [django.server       ]  "GET /get_players/ HTTP/1.1" 200 8097
2018-06-25 15:34:30,375 [Thread-6    ] [INFO ] [django.server       ]  "GET /player/ HTTP/1.1" 200 10717
2018-06-25 15:35:12,763 [Thread-13   ] [INFO ] [django.server       ]  "GET /player/ HTTP/1.1" 200 10717
2018-06-25 15:35:12,790 [Thread-16   ] [INFO ] [django.server       ]  "GET /static/rest_framework/css/prettify.css HTTP/1.1" 304 0
2018-06-25 15:35:12,791 [Thread-19   ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
2018-06-25 15:35:12,794 [Thread-15   ] [INFO ] [django.server       ]  "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 304 0
2018-06-25 15:35:12,795 [Thread-18   ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/jquery-3.3.1.min.js HTTP/1.1" 304 0
2018-06-25 15:35:12,796 [Thread-17   ] [INFO ] [django.server       ]  "GET /static/rest_framework/css/default.css HTTP/1.1" 304 0
2018-06-25 15:35:12,796 [Thread-14   ] [INFO ] [django.server       ]  "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 304 0
2018-06-25 15:35:12,802 [Thread-20   ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
2018-06-25 15:35:12,802 [Thread-21   ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
2018-06-25 15:35:12,805 [Thread-22   ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
2018-06-25 15:35:12,821 [Thread-23   ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
2018-06-25 15:35:12,880 [Thread-24   ] [INFO ] [django.server       ]  "GET /static/rest_framework/img/grid.png HTTP/1.1" 304 0
2018-06-25 15:35:35,301 [Thread-31   ] [INFO ] [django.server       ]  "GET /player HTTP/1.1" 301 0
2018-06-25 15:35:37,475 [Thread-32   ] [INFO ] [django.server       ]  "GET /player/ HTTP/1.1" 200 558
2018-06-25 15:37:46,901 [Thread-1    ] [INFO ] [django.server       ]  "GET /player/ HTTP/1.1" 200 558
2018-06-25 15:37:57,638 [Thread-3    ] [INFO ] [django.server       ]  "GET /get_players HTTP/1.1" 200 588
2018-06-25 15:38:20,657 [Thread-4    ] [INFO ] [django.server       ]  "GET / HTTP/1.1" 200 5174
2018-06-25 15:44:02,804 [Thread-1    ] [ERROR] [django.request      ]  Internal Server Error: /get_players
Traceback (most recent call last):
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/decorators.py", line 53, in handler
    return func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/player_ms/player_app/views.py", line 25, in get_players
    one_player['team'] = urllib.urlopen(MSUrls.team + '/team/' + one_player['team_id']).read()
AttributeError: module 'urllib' has no attribute 'urlopen'
2018-06-25 15:44:02,949 [Thread-1    ] [ERROR] [django.server       ]  "GET /get_players HTTP/1.1" 500 15511
2018-06-25 15:45:00,847 [Thread-1    ] [ERROR] [django.request      ]  Internal Server Error: /get_players
Traceback (most recent call last):
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/request.py", line 411, in __getattr__
    return getattr(self._request, attr)
AttributeError: 'WSGIRequest' object has no attribute 'urlopen'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/decorators.py", line 53, in handler
    return func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/player_ms/player_app/views.py", line 25, in get_players
    one_player['team'] = request.urlopen(MSUrls.team + '/team/' + one_player['team_id']).read()
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/request.py", line 413, in __getattr__
    return self.__getattribute__(attr)
AttributeError: 'Request' object has no attribute 'urlopen'
2018-06-25 15:45:01,017 [Thread-1    ] [ERROR] [django.server       ]  "GET /get_players HTTP/1.1" 500 16022
2018-06-25 15:45:21,803 [Thread-1    ] [ERROR] [django.request      ]  Internal Server Error: /get_players
Traceback (most recent call last):
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/decorators.py", line 53, in handler
    return func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/player_ms/player_app/views.py", line 25, in get_players
    one_player['team'] = request.urlopen(MSUrls.team + '/team/' + one_player['team_id']).read()
TypeError: must be str, not int
2018-06-25 15:45:21,905 [Thread-1    ] [ERROR] [django.server       ]  "GET /get_players HTTP/1.1" 500 15458
2018-06-25 15:45:33,841 [Thread-3    ] [ERROR] [django.request      ]  Internal Server Error: /get_players/
Traceback (most recent call last):
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/decorators.py", line 53, in handler
    return func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/player_ms/player_app/views.py", line 25, in get_players
    one_player['team'] = request.urlopen(MSUrls.team + '/team/' + one_player['team_id']).read()
TypeError: must be str, not int
2018-06-25 15:45:33,884 [Thread-3    ] [ERROR] [django.server       ]  "GET /get_players/ HTTP/1.1" 500 15462
2018-06-25 15:45:58,074 [Thread-1    ] [ERROR] [django.request      ]  Internal Server Error: /get_players/
Traceback (most recent call last):
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/decorators.py", line 53, in handler
    return func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/player_ms/player_app/views.py", line 25, in get_players
    one_player['team'] = request.urlopen(MSUrls.team + '/team/' + str(one_player['team_id'])).read()
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
2018-06-25 15:45:58,284 [Thread-1    ] [ERROR] [django.server       ]  "GET /get_players/ HTTP/1.1" 500 16560
2018-06-25 15:50:52,966 [Thread-1    ] [ERROR] [django.request      ]  Internal Server Error: /get_players/
Traceback (most recent call last):
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/decorators.py", line 53, in handler
    return func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/player_ms/player_app/views.py", line 25, in get_players
    one_player['team'] = request.urlopen(MSUrls.team + '/team/' + str(one_player['team_id']) + '/').read()
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
2018-06-25 15:50:53,132 [Thread-1    ] [ERROR] [django.server       ]  "GET /get_players/ HTTP/1.1" 500 16566
2018-06-25 15:51:20,845 [Thread-1    ] [INFO ] [django.server       ]  "GET /get_players/ HTTP/1.1" 200 1117
2018-06-25 15:53:04,389 [Thread-1    ] [INFO ] [django.server       ]  "GET /get_players/ HTTP/1.1" 200 1037
2018-06-25 15:53:42,422 [Thread-3    ] [INFO ] [django.server       ]  "GET /get_players/ HTTP/1.1" 200 1037
2018-06-25 15:56:42,867 [Thread-4    ] [INFO ] [django.server       ]  "GET /get_players/ HTTP/1.1" 200 1037
2018-06-25 15:56:43,868 [Thread-5    ] [INFO ] [django.server       ]  "GET /get_players/ HTTP/1.1" 200 1037
2018-06-25 15:56:44,692 [Thread-6    ] [INFO ] [django.server       ]  "GET /get_players/ HTTP/1.1" 200 1037
2018-06-25 15:56:45,438 [Thread-7    ] [INFO ] [django.server       ]  "GET /get_players/ HTTP/1.1" 200 1037
2018-06-25 15:56:45,995 [Thread-8    ] [INFO ] [django.server       ]  "GET /get_players/ HTTP/1.1" 200 1037
2018-06-25 15:56:46,445 [Thread-9    ] [INFO ] [django.server       ]  "GET /get_players/ HTTP/1.1" 200 1037
2018-06-25 15:56:48,907 [Thread-10   ] [INFO ] [django.server       ]  "GET /get_players/ HTTP/1.1" 200 1037
2018-06-25 15:57:21,088 [Thread-1    ] [INFO ] [django.server       ]  "GET /get_players/ HTTP/1.1" 200 453
2018-06-25 15:57:22,097 [Thread-3    ] [INFO ] [django.server       ]  "GET /get_players/ HTTP/1.1" 200 453
2018-06-25 15:57:23,122 [Thread-4    ] [INFO ] [django.server       ]  "GET /get_players/ HTTP/1.1" 200 453
2018-06-25 15:57:24,003 [Thread-5    ] [INFO ] [django.server       ]  "GET /get_players/ HTTP/1.1" 200 453
2018-06-25 15:57:24,818 [Thread-6    ] [INFO ] [django.server       ]  "GET /get_players/ HTTP/1.1" 200 453
2018-06-25 15:57:31,312 [Thread-7    ] [INFO ] [django.server       ]  "GET /get_players/ HTTP/1.1" 200 453
2018-06-25 15:57:32,020 [Thread-8    ] [INFO ] [django.server       ]  "GET /get_players/ HTTP/1.1" 200 453
2018-06-25 15:57:33,045 [Thread-9    ] [INFO ] [django.server       ]  "GET /get_players/ HTTP/1.1" 200 453
2018-06-25 16:16:45,299 [Thread-1    ] [ERROR] [django.request      ]  Internal Server Error: /get_players/
Traceback (most recent call last):
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/decorators.py", line 53, in handler
    return func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/player_ms/player_app/views.py", line 31, in get_players
    request.urlopen(MSUrls.team + 'get_team_list/', data=team_id_list)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1064, in _send_output
    + b'\r\n'
TypeError: object of type 'int' has no len()
2018-06-25 16:16:45,545 [Thread-1    ] [ERROR] [django.server       ]  "GET /get_players/ HTTP/1.1" 500 17323
2018-06-25 16:18:05,331 [Thread-1    ] [ERROR] [django.request      ]  Internal Server Error: /get_players/
Traceback (most recent call last):
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/decorators.py", line 53, in handler
    return func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/player_ms/player_app/views.py", line 31, in get_players
    request.urlopen(MSUrls.team + 'get_team_list/', data={'team_ids': team_id_list})
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1064, in _send_output
    + b'\r\n'
TypeError: can't concat str to bytes
2018-06-25 16:18:05,579 [Thread-1    ] [ERROR] [django.server       ]  "GET /get_players/ HTTP/1.1" 500 17321
2018-06-25 16:18:46,498 [Thread-1    ] [ERROR] [django.request      ]  Internal Server Error: /get_players/
Traceback (most recent call last):
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/decorators.py", line 53, in handler
    return func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/player_ms/player_app/views.py", line 32, in get_players
    {'team_ids': team_id_list}
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 524, in open
    req = meth(req)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1248, in do_request_
    raise TypeError(msg)
TypeError: POST data should be bytes, an iterable of bytes, or a file object. It cannot be of type str.
2018-06-25 16:18:46,700 [Thread-1    ] [ERROR] [django.server       ]  "GET /get_players/ HTTP/1.1" 500 16048
2018-06-25 16:20:01,617 [Thread-1    ] [ERROR] [django.request      ]  Internal Server Error: /get_players/
Traceback (most recent call last):
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/decorators.py", line 53, in handler
    return func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/player_ms/player_app/views.py", line 31, in get_players
    request.urlopen(MSUrls.team + 'get_team_list/', data={'team_ids': team_id_list})
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1064, in _send_output
    + b'\r\n'
TypeError: can't concat str to bytes
2018-06-25 16:20:01,872 [Thread-1    ] [ERROR] [django.server       ]  "GET /get_players/ HTTP/1.1" 500 17321
2018-06-25 16:20:34,706 [Thread-3    ] [ERROR] [django.request      ]  Internal Server Error: /get_players/
Traceback (most recent call last):
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/decorators.py", line 53, in handler
    return func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/player_ms/player_app/views.py", line 31, in get_players
    request.urlopen(MSUrls.team + 'get_team_list/', data={'team_ids': team_id_list})
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1064, in _send_output
    + b'\r\n'
TypeError: can't concat str to bytes
2018-06-25 16:20:34,737 [Thread-3    ] [ERROR] [django.server       ]  "GET /get_players/ HTTP/1.1" 500 17321
2018-06-25 16:23:26,054 [Thread-1    ] [ERROR] [django.request      ]  Internal Server Error: /get_players/
Traceback (most recent call last):
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/decorators.py", line 53, in handler
    return func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/player_ms/player_app/views.py", line 31, in get_players
    request.urlopen(MSUrls.team + 'get_team_list/', data=team_id_list)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1064, in _send_output
    + b'\r\n'
TypeError: object of type 'int' has no len()
2018-06-25 16:23:26,224 [Thread-1    ] [ERROR] [django.server       ]  "GET /get_players/ HTTP/1.1" 500 17323
2018-06-25 16:23:58,655 [Thread-3    ] [ERROR] [django.request      ]  Internal Server Error: /get_players/
Traceback (most recent call last):
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/decorators.py", line 53, in handler
    return func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/player_ms/player_app/views.py", line 31, in get_players
    request.urlopen(MSUrls.team + 'get_team_list/', data=team_id_list)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1064, in _send_output
    + b'\r\n'
TypeError: object of type 'int' has no len()
2018-06-25 16:23:58,831 [Thread-3    ] [ERROR] [django.server       ]  "GET /get_players/ HTTP/1.1" 500 17323
2018-06-25 16:25:28,736 [Thread-1    ] [ERROR] [django.request      ]  Internal Server Error: /get_players/
Traceback (most recent call last):
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/decorators.py", line 53, in handler
    return func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/player_ms/player_app/views.py", line 31, in get_players
    request.urlopen(MSUrls.team + 'get_team_list/', data={'team_ids': json.dumps(team_id_list)})
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1064, in _send_output
    + b'\r\n'
TypeError: can't concat str to bytes
2018-06-25 16:25:28,970 [Thread-1    ] [ERROR] [django.server       ]  "GET /get_players/ HTTP/1.1" 500 17333
2018-06-25 16:27:02,864 [Thread-3    ] [ERROR] [django.request      ]  Internal Server Error: /get_players/
Traceback (most recent call last):
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/decorators.py", line 53, in handler
    return func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/player_ms/player_app/views.py", line 31, in get_players
    request.urlopen(MSUrls.team + 'get_team_list/', data={'team_ids': json.dumps(team_id_list)})
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1064, in _send_output
    + b'\r\n'
TypeError: can't concat str to bytes
2018-06-25 16:27:03,045 [Thread-3    ] [ERROR] [django.server       ]  "GET /get_players/ HTTP/1.1" 500 17333
2018-06-25 16:27:30,135 [Thread-1    ] [ERROR] [django.request      ]  Internal Server Error: /get_players/
Traceback (most recent call last):
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/decorators.py", line 53, in handler
    return func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/player_ms/player_app/views.py", line 31, in get_players
    request.urlopen(MSUrls.team + 'get_team_list/', data={'team_ids': team_id_list})
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1064, in _send_output
    + b'\r\n'
TypeError: can't concat str to bytes
2018-06-25 16:27:30,226 [Thread-1    ] [ERROR] [django.server       ]  "GET /get_players/ HTTP/1.1" 500 17321
2018-06-25 16:27:39,814 [Thread-3    ] [ERROR] [django.request      ]  Internal Server Error: /get_players/
Traceback (most recent call last):
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/decorators.py", line 53, in handler
    return func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/player_ms/player_app/views.py", line 31, in get_players
    request.urlopen(MSUrls.team + 'get_team_list/', data={'team_ids': team_id_list})
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1064, in _send_output
    + b'\r\n'
TypeError: can't concat str to bytes
2018-06-25 16:27:39,839 [Thread-3    ] [ERROR] [django.server       ]  "GET /get_players/ HTTP/1.1" 500 17321
2018-06-25 16:28:37,280 [Thread-1    ] [ERROR] [django.request      ]  Internal Server Error: /get_players/
Traceback (most recent call last):
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/decorators.py", line 53, in handler
    return func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/player_ms/player_app/views.py", line 33, in get_players
    request.urlopen(MSUrls.team + 'get_team_list/', data={'team_ids': team_id_list})
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1064, in _send_output
    + b'\r\n'
TypeError: can't concat str to bytes
2018-06-25 16:28:37,744 [Thread-1    ] [ERROR] [django.server       ]  "GET /get_players/ HTTP/1.1" 500 17321
2018-06-25 16:29:15,181 [Thread-1    ] [ERROR] [django.request      ]  Internal Server Error: /get_players/
Traceback (most recent call last):
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/decorators.py", line 53, in handler
    return func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/player_ms/player_app/views.py", line 36, in get_players
    request.urlopen(MSUrls.team + 'get_team_list/', data={'team_ids': team_id_list})
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1064, in _send_output
    + b'\r\n'
TypeError: can't concat str to bytes
2018-06-25 16:29:15,538 [Thread-1    ] [ERROR] [django.server       ]  "GET /get_players/ HTTP/1.1" 500 17321
2018-06-25 16:29:41,970 [Thread-1    ] [ERROR] [django.request      ]  Internal Server Error: /get_players/
Traceback (most recent call last):
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/decorators.py", line 53, in handler
    return func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/player_ms/player_app/views.py", line 36, in get_players
    request.urlopen(MSUrls.team + 'get_team_list/', data={'team_ids': str(team_id_list)})
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1064, in _send_output
    + b'\r\n'
TypeError: can't concat str to bytes
2018-06-25 16:29:42,041 [Thread-1    ] [ERROR] [django.server       ]  "GET /get_players/ HTTP/1.1" 500 17326
2018-06-25 16:30:44,831 [Thread-3    ] [ERROR] [django.request      ]  Internal Server Error: /get_players/
Traceback (most recent call last):
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/decorators.py", line 53, in handler
    return func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/player_ms/player_app/views.py", line 36, in get_players
    request.urlopen(MSUrls.team + 'get_team_list/', data={'team_ids': str(team_id_list)})
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1064, in _send_output
    + b'\r\n'
TypeError: can't concat str to bytes
2018-06-25 16:30:44,873 [Thread-3    ] [ERROR] [django.server       ]  "GET /get_players/ HTTP/1.1" 500 17326
2018-06-25 16:31:27,170 [Thread-1    ] [ERROR] [django.request      ]  Internal Server Error: /get_players/
Traceback (most recent call last):
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/decorators.py", line 53, in handler
    return func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/player_ms/player_app/views.py", line 36, in get_players
    request.urlopen(MSUrls.team + 'get_team_list/', data=json.dumps({'team_ids': str(team_id_list)}))
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 524, in open
    req = meth(req)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1248, in do_request_
    raise TypeError(msg)
TypeError: POST data should be bytes, an iterable of bytes, or a file object. It cannot be of type str.
2018-06-25 16:31:27,250 [Thread-1    ] [ERROR] [django.server       ]  "GET /get_players/ HTTP/1.1" 500 16115
2018-06-25 16:34:24,660 [Thread-1    ] [ERROR] [django.request      ]  Internal Server Error: /get_players/
Traceback (most recent call last):
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/decorators.py", line 53, in handler
    return func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/player_ms/player_app/views.py", line 38, in get_players
    request.urlopen(MSUrls.team + 'get_team_list/', data=data)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 348, in loads
    'not {!r}'.format(s.__class__.__name__))
TypeError: the JSON object must be str, bytes or bytearray, not 'HTTPResponse'
2018-06-25 16:34:24,854 [Thread-1    ] [ERROR] [django.server       ]  "GET /get_players/ HTTP/1.1" 500 15720
2018-06-25 16:42:36,431 [Thread-1    ] [ERROR] [django.request      ]  Internal Server Error: /get_players/
Traceback (most recent call last):
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/decorators.py", line 53, in handler
    return func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/player_ms/player_app/views.py", line 38, in get_players
    request.urlopen(MSUrls.team + 'get_team_list/', data=data)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 524, in open
    req = meth(req)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1248, in do_request_
    raise TypeError(msg)
TypeError: POST data should be bytes, an iterable of bytes, or a file object. It cannot be of type str.
2018-06-25 16:42:36,613 [Thread-1    ] [ERROR] [django.server       ]  "GET /get_players/ HTTP/1.1" 500 16076
2018-06-25 16:42:56,654 [Thread-3    ] [ERROR] [django.request      ]  Internal Server Error: /get_players/
Traceback (most recent call last):
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/decorators.py", line 53, in handler
    return func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/player_ms/player_app/views.py", line 38, in get_players
    request.urlopen(MSUrls.team + 'get_team_list/', data=data)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 524, in open
    req = meth(req)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1248, in do_request_
    raise TypeError(msg)
TypeError: POST data should be bytes, an iterable of bytes, or a file object. It cannot be of type str.
2018-06-25 16:42:56,684 [Thread-3    ] [ERROR] [django.server       ]  "GET /get_players/ HTTP/1.1" 500 16076
2018-06-25 16:44:05,280 [Thread-1    ] [ERROR] [django.request      ]  Internal Server Error: /get_players/
Traceback (most recent call last):
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/decorators.py", line 53, in handler
    return func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/player_ms/player_app/views.py", line 38, in get_players
    request.urlopen(MSUrls.team + 'get_team_list/', data=data).read()
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 524, in open
    req = meth(req)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1248, in do_request_
    raise TypeError(msg)
TypeError: POST data should be bytes, an iterable of bytes, or a file object. It cannot be of type str.
2018-06-25 16:44:05,483 [Thread-1    ] [ERROR] [django.server       ]  "GET /get_players/ HTTP/1.1" 500 16083
2018-06-25 16:44:33,200 [Thread-1    ] [ERROR] [django.request      ]  Internal Server Error: /get_players/
Traceback (most recent call last):
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/decorators.py", line 53, in handler
    return func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/player_ms/player_app/views.py", line 38, in get_players
    request.urlopen(MSUrls.team + 'get_team_list/', data={'team_ids': team_id_list}).read()
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1064, in _send_output
    + b'\r\n'
TypeError: can't concat str to bytes
2018-06-25 16:44:33,425 [Thread-1    ] [ERROR] [django.server       ]  "GET /get_players/ HTTP/1.1" 500 17328
2018-06-25 16:45:25,467 [Thread-1    ] [ERROR] [django.request      ]  Internal Server Error: /get_players/
Traceback (most recent call last):
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/decorators.py", line 53, in handler
    return func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/player_ms/player_app/views.py", line 38, in get_players
    request.urlopen(MSUrls.team + 'get_team_list/', data=data).read()
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 524, in open
    req = meth(req)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1248, in do_request_
    raise TypeError(msg)
TypeError: POST data should be bytes, an iterable of bytes, or a file object. It cannot be of type str.
2018-06-25 16:45:25,614 [Thread-1    ] [ERROR] [django.server       ]  "GET /get_players/ HTTP/1.1" 500 16083
2018-06-25 16:46:25,947 [Thread-1    ] [INFO ] [django.server       ]  "GET /get_players/ HTTP/1.1" 200 932
2018-06-25 16:46:33,029 [Thread-3    ] [INFO ] [django.server       ]  "GET /get_players/ HTTP/1.1" 200 932
2018-06-25 16:46:34,767 [Thread-4    ] [INFO ] [django.server       ]  "GET /get_players/ HTTP/1.1" 200 932
2018-06-25 16:46:35,554 [Thread-5    ] [INFO ] [django.server       ]  "GET /get_players/ HTTP/1.1" 200 932
2018-06-25 16:46:36,238 [Thread-6    ] [INFO ] [django.server       ]  "GET /get_players/ HTTP/1.1" 200 932
2018-06-25 16:46:36,928 [Thread-7    ] [INFO ] [django.server       ]  "GET /get_players/ HTTP/1.1" 200 932
2018-06-25 16:46:37,746 [Thread-8    ] [INFO ] [django.server       ]  "GET /get_players/ HTTP/1.1" 200 932
2018-06-25 16:46:38,430 [Thread-9    ] [INFO ] [django.server       ]  "GET /get_players/ HTTP/1.1" 200 932
2018-06-25 16:46:48,602 [Thread-10   ] [INFO ] [django.server       ]  "GET /get_players/ HTTP/1.1" 200 932
2018-06-25 16:47:11,606 [Thread-1    ] [INFO ] [django.server       ]  "GET /get_players/ HTTP/1.1" 200 932
2018-06-25 16:47:17,744 [Thread-3    ] [INFO ] [django.server       ]  "GET /get_players/ HTTP/1.1" 200 932
2018-06-25 16:54:10,824 [Thread-1    ] [INFO ] [django.server       ]  "GET /fake_100_players/ HTTP/1.1" 200 7
2018-06-25 16:54:17,877 [Thread-3    ] [INFO ] [django.server       ]  "GET /get_players/ HTTP/1.1" 200 31526
2018-06-25 16:54:24,445 [Thread-4    ] [INFO ] [django.server       ]  "GET /get_players/ HTTP/1.1" 200 31526
2018-06-25 16:54:25,584 [Thread-5    ] [INFO ] [django.server       ]  "GET /get_players/ HTTP/1.1" 200 31526
2018-06-25 16:54:27,454 [Thread-6    ] [INFO ] [django.server       ]  "GET /get_players/ HTTP/1.1" 200 31526
2018-06-25 16:54:43,711 [Thread-7    ] [INFO ] [django.server       ]  "GET /fake_100_players/ HTTP/1.1" 200 7
2018-06-25 16:54:46,738 [Thread-8    ] [INFO ] [django.server       ]  "GET /fake_100_players/ HTTP/1.1" 200 7
2018-06-25 16:54:49,366 [Thread-9    ] [INFO ] [django.server       ]  "GET /fake_100_players/ HTTP/1.1" 200 7
2018-06-25 16:54:58,154 [Thread-10   ] [INFO ] [django.server       ]  "GET /get_players/ HTTP/1.1" 200 123602
2018-06-25 16:55:02,988 [Thread-11   ] [INFO ] [django.server       ]  "GET /get_players/ HTTP/1.1" 200 123602
2018-06-25 16:55:11,853 [Thread-12   ] [INFO ] [django.server       ]  "GET /get_players/ HTTP/1.1" 200 123602
2018-06-25 16:55:33,123 [Thread-13   ] [INFO ] [django.server       ]  "GET /get_players/ HTTP/1.1" 200 123602
2018-06-25 16:55:59,048 [Thread-14   ] [WARNI] [django.request      ]  Not Found: /players
2018-06-25 16:55:59,064 [Thread-14   ] [WARNI] [django.server       ]  "GET /players HTTP/1.1" 404 3542
2018-06-25 16:56:01,949 [Thread-15   ] [INFO ] [django.server       ]  "GET /player HTTP/1.1" 301 0
2018-06-25 16:56:02,404 [Thread-16   ] [INFO ] [django.server       ]  "GET /player/ HTTP/1.1" 200 162987
2018-06-25 16:56:02,505 [Thread-18   ] [INFO ] [django.server       ]  "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 304 0
2018-06-25 16:56:02,505 [Thread-17   ] [INFO ] [django.server       ]  "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 304 0
2018-06-25 16:56:02,505 [Thread-20   ] [INFO ] [django.server       ]  "GET /static/rest_framework/css/default.css HTTP/1.1" 304 0
2018-06-25 16:56:02,506 [Thread-22   ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
2018-06-25 16:56:02,507 [Thread-21   ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/jquery-3.3.1.min.js HTTP/1.1" 304 0
2018-06-25 16:56:02,508 [Thread-19   ] [INFO ] [django.server       ]  "GET /static/rest_framework/css/prettify.css HTTP/1.1" 304 0
2018-06-25 16:56:02,515 [Thread-24   ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
2018-06-25 16:56:02,516 [Thread-23   ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
2018-06-25 16:56:02,517 [Thread-26   ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
2018-06-25 16:56:02,517 [Thread-25   ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
2018-06-25 16:56:02,580 [Thread-27   ] [INFO ] [django.server       ]  "GET /static/rest_framework/img/grid.png HTTP/1.1" 304 0
2018-06-25 16:57:50,421 [Thread-28   ] [INFO ] [django.server       ]  "GET /get_players/ HTTP/1.1" 200 123602
2018-06-25 16:57:54,221 [Thread-29   ] [INFO ] [django.server       ]  "GET /get_players/ HTTP/1.1" 200 123602
2018-06-25 16:59:48,648 [Thread-30   ] [INFO ] [django.server       ]  "GET /get_players/ HTTP/1.1" 200 123602
2018-06-25 16:59:52,059 [Thread-31   ] [INFO ] [django.server       ]  "GET /get_players/ HTTP/1.1" 200 123602
2018-06-25 17:05:02,824 [Thread-32   ] [INFO ] [django.server       ]  "GET /admin HTTP/1.1" 301 0
2018-06-25 17:05:02,896 [Thread-33   ] [INFO ] [django.server       ]  "GET /admin/ HTTP/1.1" 302 0
2018-06-25 17:05:03,040 [Thread-34   ] [INFO ] [django.server       ]  "GET /admin/login/?next=/admin/ HTTP/1.1" 200 1859
2018-06-25 17:05:03,083 [Thread-35   ] [INFO ] [django.server       ]  "GET /static/admin/css/base.css HTTP/1.1" 200 16106
2018-06-25 17:05:03,083 [Thread-36   ] [INFO ] [django.server       ]  "GET /static/admin/css/login.css HTTP/1.1" 200 1203
2018-06-25 17:05:03,100 [Thread-37   ] [INFO ] [django.server       ]  "GET /static/admin/css/responsive.css HTTP/1.1" 200 17894
2018-06-25 17:05:03,129 [Thread-38   ] [INFO ] [django.server       ]  "GET /static/admin/css/fonts.css HTTP/1.1" 200 423
2018-06-25 17:05:03,137 [Thread-39   ] [INFO ] [django.server       ]  "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 80304
2018-06-25 17:05:03,141 [Thread-40   ] [INFO ] [django.server       ]  "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 81348
2018-06-25 17:05:37,322 [Thread-41   ] [INFO ] [django.server       ]  "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
2018-06-25 17:05:37,361 [Thread-42   ] [INFO ] [django.server       ]  "GET /admin/ HTTP/1.1" 200 2988
2018-06-25 17:05:37,390 [Thread-43   ] [INFO ] [django.server       ]  "GET /static/admin/css/dashboard.css HTTP/1.1" 200 412
2018-06-25 17:05:37,408 [Thread-44   ] [INFO ] [django.server       ]  "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
2018-06-25 17:05:37,409 [Thread-45   ] [INFO ] [django.server       ]  "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
2018-06-25 17:05:37,446 [Thread-46   ] [INFO ] [django.server       ]  "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 82564
2018-06-25 17:05:43,519 [Thread-47   ] [WARNI] [django.request      ]  Not Found: /admin/player
2018-06-25 17:05:43,519 [Thread-47   ] [WARNI] [django.server       ]  "GET /admin/player HTTP/1.1" 404 5298
2018-06-25 17:05:47,114 [Thread-48   ] [INFO ] [django.server       ]  "GET /admin/ HTTP/1.1" 200 2988
2018-06-25 17:06:48,669 [Thread-1    ] [INFO ] [django.server       ]  "GET /admin/ HTTP/1.1" 200 3658
2018-06-25 17:06:49,868 [Thread-3    ] [INFO ] [django.server       ]  "GET /admin/player_app/player/ HTTP/1.1" 200 41784
2018-06-25 17:06:49,904 [Thread-4    ] [INFO ] [django.server       ]  "GET /static/admin/css/changelists.css HTTP/1.1" 200 6170
2018-06-25 17:06:49,907 [Thread-7    ] [INFO ] [django.server       ]  "GET /static/admin/js/jquery.init.js HTTP/1.1" 200 363
2018-06-25 17:06:49,909 [Thread-8    ] [INFO ] [django.server       ]  "GET /static/admin/js/core.js HTTP/1.1" 200 7134
2018-06-25 17:06:49,918 [Thread-10   ] [INFO ] [django.server       ]  "GET /static/admin/js/actions.js HTTP/1.1" 200 6502
2018-06-25 17:06:49,918 [Thread-9    ] [INFO ] [django.server       ]  "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 6897
2018-06-25 17:06:49,934 [Thread-5    ] [INFO ] [django.server       ]  "GET /admin/jsi18n/ HTTP/1.1" 200 3185
2018-06-25 17:06:49,957 [Thread-6    ] [INFO ] [django.server       ]  "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 258648
2018-06-25 17:06:49,969 [Thread-12   ] [INFO ] [django.server       ]  "GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1538
2018-06-25 17:06:49,971 [Thread-11   ] [INFO ] [django.server       ]  "GET /static/admin/js/urlify.js HTTP/1.1" 200 8729
2018-06-25 17:06:49,982 [Thread-13   ] [INFO ] [django.server       ]  "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 128820
2018-06-25 17:06:49,983 [Thread-14   ] [INFO ] [django.server       ]  "GET /static/admin/img/search.svg HTTP/1.1" 200 458
2018-06-25 17:06:50,050 [Thread-15   ] [INFO ] [django.server       ]  "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
2018-06-25 17:13:19,002 [Thread-1    ] [INFO ] [django.server       ]  "GET /admin/player_app/player/ HTTP/1.1" 200 41784
2018-06-25 17:13:19,080 [Thread-3    ] [INFO ] [django.server       ]  "GET /admin/jsi18n/ HTTP/1.1" 200 3185
2018-06-25 17:13:20,791 [Thread-4    ] [INFO ] [django.server       ]  "GET /admin/player_app/player/ HTTP/1.1" 200 41784
2018-06-25 17:13:20,828 [Thread-5    ] [INFO ] [django.server       ]  "GET /admin/jsi18n/ HTTP/1.1" 200 3185
2018-06-25 17:13:38,082 [Thread-1    ] [INFO ] [django.server       ]  "GET /admin/player_app/player/ HTTP/1.1" 200 41973
2018-06-25 17:13:38,147 [Thread-3    ] [INFO ] [django.server       ]  "GET /admin/jsi18n/ HTTP/1.1" 200 3185
2018-06-25 17:13:39,879 [Thread-4    ] [INFO ] [django.server       ]  "GET /admin/player_app/player/export/? HTTP/1.1" 200 2676
2018-06-25 17:13:39,904 [Thread-5    ] [INFO ] [django.server       ]  "GET /static/admin/css/forms.css HTTP/1.1" 200 8173
2018-06-25 17:13:39,919 [Thread-6    ] [INFO ] [django.server       ]  "GET /static/admin/css/widgets.css HTTP/1.1" 200 10340
2018-06-25 17:13:42,788 [Thread-7    ] [INFO ] [django.server       ]  "POST /admin/player_app/player/export/? HTTP/1.1" 200 71680
2018-06-25 17:15:19,169 [Thread-8    ] [INFO ] [django.server       ]  "GET /admin/player_app/player/import HTTP/1.1" 301 0
2018-06-25 17:15:19,368 [Thread-9    ] [INFO ] [django.server       ]  "GET /admin/player_app/player/import/ HTTP/1.1" 200 2999
2018-06-25 17:15:31,048 [Thread-14   ] [INFO ] [django.server       ]  "POST /admin/player_app/player/import/ HTTP/1.1" 200 83
2018-06-25 17:17:56,702 [Thread-15   ] [INFO ] [django.server       ]  "GET /admin/player_app/player/import/ HTTP/1.1" 200 2999
2018-06-25 17:25:21,908 [Thread-21   ] [INFO ] [django.server       ]  "GET /player/ HTTP/1.1" 200 162987
2018-06-25 17:25:21,937 [Thread-23   ] [INFO ] [django.server       ]  "GET /static/rest_framework/css/prettify.css HTTP/1.1" 304 0
2018-06-25 17:25:21,938 [Thread-22   ] [INFO ] [django.server       ]  "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 304 0
2018-06-25 17:25:21,939 [Thread-24   ] [INFO ] [django.server       ]  "GET /static/rest_framework/css/default.css HTTP/1.1" 304 0
2018-06-25 17:25:21,942 [Thread-25   ] [INFO ] [django.server       ]  "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 304 0
2018-06-25 17:25:21,954 [Thread-26   ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/jquery-3.3.1.min.js HTTP/1.1" 304 0
2018-06-25 17:25:21,955 [Thread-27   ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
2018-06-25 17:25:21,957 [Thread-28   ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
2018-06-25 17:25:21,959 [Thread-29   ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
2018-06-25 17:25:21,961 [Thread-30   ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
2018-06-25 17:25:21,962 [Thread-31   ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
2018-06-25 17:25:22,017 [Thread-32   ] [INFO ] [django.server       ]  "GET /static/rest_framework/img/grid.png HTTP/1.1" 304 0
2018-06-25 17:25:32,618 [Thread-33   ] [WARNI] [django.request      ]  Not Found: /players_list
2018-06-25 17:25:32,636 [Thread-33   ] [WARNI] [django.server       ]  "GET /players_list HTTP/1.1" 404 3557
2018-06-25 17:25:38,733 [Thread-34   ] [INFO ] [django.server       ]  "GET /get_players HTTP/1.1" 200 351841
2018-06-25 17:25:44,931 [Thread-39   ] [INFO ] [django.server       ]  "GET /get_players HTTP/1.1" 200 351841
2018-06-25 17:26:36,881 [Thread-45   ] [INFO ] [django.server       ]  "GET /fake_100_players HTTP/1.1" 200 5257
2018-06-25 17:26:42,987 [Thread-46   ] [INFO ] [django.server       ]  "GET /player/ HTTP/1.1" 200 201085
2018-06-25 17:26:53,801 [Thread-51   ] [INFO ] [django.server       ]  "GET /get_players/ HTTP/1.1" 200 437546
2018-06-25 17:27:10,524 [Thread-57   ] [INFO ] [django.server       ]  "GET /get_players/ HTTP/1.1" 200 154300
2018-06-25 17:27:21,630 [Thread-58   ] [INFO ] [django.server       ]  "GET /get_players/ HTTP/1.1" 200 154300
2018-06-25 17:27:26,336 [Thread-59   ] [INFO ] [django.server       ]  "GET /get_players/ HTTP/1.1" 200 154300
2018-06-25 17:27:49,038 [Thread-60   ] [INFO ] [django.server       ]  "GET /player/ HTTP/1.1" 200 70926
2018-06-25 17:28:06,620 [Thread-61   ] [INFO ] [django.server       ]  "GET /get_players HTTP/1.1" 200 154300
2018-06-25 17:29:59,648 [Thread-62   ] [ERROR] [django.request      ]  Internal Server Error: /get_players/asd
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/decorators.py", line 53, in handler
    return func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/player_ms/player_app/views.py", line 33, in get_players
    request.urlopen(MSUrls.team + 'get_team_list/', data=data).read()
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 61] Connection refused>
2018-06-25 17:29:59,989 [Thread-62   ] [ERROR] [django.server       ]  "GET /get_players/asd HTTP/1.1" 500 208058
2018-06-25 17:30:06,882 [Thread-63   ] [INFO ] [django.server       ]  "GET /player/ HTTP/1.1" 200 201085
2018-06-25 17:30:08,853 [Thread-64   ] [WARNI] [django.request      ]  Not Found: /player/4/8
2018-06-25 17:30:08,853 [Thread-64   ] [WARNI] [django.server       ]  "GET /player/4/8 HTTP/1.1" 404 3551
2018-06-25 17:38:20,563 [Thread-1    ] [INFO ] [django.server       ]  "GET /get_team_players/1 HTTP/1.1" 301 0
2018-06-25 17:38:23,752 [Thread-3    ] [INFO ] [django.server       ]  "GET /get_team_players/1/ HTTP/1.1" 200 185
2018-06-25 17:38:27,884 [Thread-4    ] [INFO ] [django.server       ]  "GET /get_team_players/2/ HTTP/1.1" 200 70540
2018-06-25 17:38:51,340 [Thread-5    ] [INFO ] [django.server       ]  "GET /get_team_players/3/ HTTP/1.1" 200 98
2018-06-25 17:38:57,577 [Thread-6    ] [INFO ] [django.server       ]  "GET /get_team_players/4/ HTTP/1.1" 200 2
2018-06-25 17:39:00,699 [Thread-7    ] [INFO ] [django.server       ]  "GET /get_team_players/1/ HTTP/1.1" 200 185
2018-06-25 17:43:02,603 [Thread-8    ] [INFO ] [django.server       ]  "GET /get_team_players/1/ HTTP/1.1" 200 185
2018-06-25 17:43:37,837 [Thread-9    ] [INFO ] [django.server       ]  "GET /get_team_players/1/ HTTP/1.1" 200 185
2018-06-25 17:44:22,731 [Thread-10   ] [INFO ] [django.server       ]  "GET /get_team_players/1/ HTTP/1.1" 200 185
2018-06-25 17:44:37,996 [Thread-11   ] [INFO ] [django.server       ]  "GET /get_team_players/1/ HTTP/1.1" 200 185
2018-06-25 17:44:52,849 [Thread-12   ] [INFO ] [django.server       ]  "GET /get_team_players/3/ HTTP/1.1" 200 98
2018-06-25 17:44:55,662 [Thread-13   ] [INFO ] [django.server       ]  "GET /get_team_players/1/ HTTP/1.1" 200 185
2018-06-25 17:44:58,105 [Thread-14   ] [INFO ] [django.server       ]  "GET /get_team_players/2/ HTTP/1.1" 200 70540
2018-06-25 17:46:25,301 [Thread-15   ] [INFO ] [django.server       ]  "GET /get_players/ HTTP/1.1" 200 154300
2018-06-25 17:47:00,586 [Thread-16   ] [INFO ] [django.server       ]  "GET /get_team_players/2/ HTTP/1.1" 200 70540
2018-06-25 17:47:08,799 [Thread-17   ] [INFO ] [django.server       ]  "GET /get_team_players/1/ HTTP/1.1" 200 185
2018-06-25 17:47:13,142 [Thread-18   ] [INFO ] [django.server       ]  "GET /get_team_players/2/ HTTP/1.1" 200 70540
2018-06-25 17:47:17,440 [Thread-19   ] [INFO ] [django.server       ]  "GET /get_team_players/3/ HTTP/1.1" 200 98
2018-06-25 17:50:11,938 [Thread-20   ] [INFO ] [django.server       ]  "GET /get_team_players/1/ HTTP/1.1" 200 185
2018-06-25 17:50:14,596 [Thread-21   ] [INFO ] [django.server       ]  "GET /get_team_players/2/ HTTP/1.1" 200 70540
2018-06-25 17:52:18,922 [Thread-22   ] [INFO ] [django.server       ]  "GET /get_team_players/1/ HTTP/1.1" 200 185
2018-06-25 17:52:22,769 [Thread-23   ] [INFO ] [django.server       ]  "GET /get_team_players/2/ HTTP/1.1" 200 70540
2018-06-25 17:52:25,865 [Thread-24   ] [INFO ] [django.server       ]  "GET /get_team_players/3/ HTTP/1.1" 200 98
2018-06-25 17:54:49,052 [Thread-25   ] [INFO ] [django.server       ]  "GET /get_team_players/1/ HTTP/1.1" 200 185
2018-06-25 17:54:53,932 [Thread-26   ] [INFO ] [django.server       ]  "GET /get_team_players/2/ HTTP/1.1" 200 70540
2018-06-25 17:55:28,579 [Thread-27   ] [INFO ] [django.server       ]  "GET /admin/ HTTP/1.1" 302 0
2018-06-25 17:55:28,988 [Thread-28   ] [INFO ] [django.server       ]  "GET /admin/login/?next=/admin/ HTTP/1.1" 200 1859
2018-06-25 17:55:29,026 [Thread-29   ] [INFO ] [django.server       ]  "GET /static/admin/css/base.css HTTP/1.1" 304 0
2018-06-25 17:55:29,027 [Thread-30   ] [INFO ] [django.server       ]  "GET /static/admin/css/login.css HTTP/1.1" 304 0
2018-06-25 17:55:29,027 [Thread-31   ] [INFO ] [django.server       ]  "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
2018-06-25 17:55:29,163 [Thread-32   ] [INFO ] [django.server       ]  "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
2018-06-25 17:55:29,174 [Thread-33   ] [INFO ] [django.server       ]  "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
2018-06-25 17:55:29,210 [Thread-34   ] [INFO ] [django.server       ]  "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
2018-06-25 17:55:33,792 [Thread-35   ] [INFO ] [django.server       ]  "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
2018-06-25 17:55:33,868 [Thread-36   ] [INFO ] [django.server       ]  "GET /admin/ HTTP/1.1" 200 3658
2018-06-25 17:55:33,883 [Thread-37   ] [INFO ] [django.server       ]  "GET /static/admin/css/dashboard.css HTTP/1.1" 304 0
2018-06-25 17:55:33,913 [Thread-38   ] [INFO ] [django.server       ]  "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
2018-06-25 17:55:33,915 [Thread-39   ] [INFO ] [django.server       ]  "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
2018-06-25 17:55:33,918 [Thread-40   ] [INFO ] [django.server       ]  "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
2018-06-25 17:55:35,966 [Thread-41   ] [INFO ] [django.server       ]  "GET /admin/player_app/player/ HTTP/1.1" 200 41926
2018-06-25 17:55:36,007 [Thread-42   ] [INFO ] [django.server       ]  "GET /static/admin/css/changelists.css HTTP/1.1" 304 0
2018-06-25 17:55:36,010 [Thread-44   ] [INFO ] [django.server       ]  "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
2018-06-25 17:55:36,012 [Thread-46   ] [INFO ] [django.server       ]  "GET /static/admin/js/core.js HTTP/1.1" 304 0
2018-06-25 17:55:36,012 [Thread-45   ] [INFO ] [django.server       ]  "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
2018-06-25 17:55:36,018 [Thread-47   ] [INFO ] [django.server       ]  "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
2018-06-25 17:55:36,023 [Thread-48   ] [INFO ] [django.server       ]  "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
2018-06-25 17:55:36,023 [Thread-49   ] [INFO ] [django.server       ]  "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
2018-06-25 17:55:36,025 [Thread-50   ] [INFO ] [django.server       ]  "GET /static/admin/js/actions.js HTTP/1.1" 304 0
2018-06-25 17:55:36,026 [Thread-51   ] [INFO ] [django.server       ]  "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
2018-06-25 17:55:36,029 [Thread-52   ] [INFO ] [django.server       ]  "GET /static/admin/img/search.svg HTTP/1.1" 304 0
2018-06-25 17:55:36,071 [Thread-43   ] [INFO ] [django.server       ]  "GET /admin/jsi18n/ HTTP/1.1" 200 3185
2018-06-25 17:55:36,128 [Thread-53   ] [INFO ] [django.server       ]  "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 304 0
2018-06-25 17:55:37,857 [Thread-54   ] [INFO ] [django.server       ]  "GET /admin/player_app/player/export/? HTTP/1.1" 200 2676
2018-06-25 17:55:37,872 [Thread-55   ] [INFO ] [django.server       ]  "GET /static/admin/css/forms.css HTTP/1.1" 304 0
2018-06-25 17:55:37,888 [Thread-56   ] [INFO ] [django.server       ]  "GET /static/admin/css/widgets.css HTTP/1.1" 304 0
2018-06-25 17:55:40,412 [Thread-57   ] [INFO ] [django.server       ]  "POST /admin/player_app/player/export/? HTTP/1.1" 200 88064
2018-06-25 18:01:01,564 [Thread-58   ] [INFO ] [django.server       ]  "GET /get_team_players/1/ HTTP/1.1" 200 185
2018-06-26 11:24:49,687 [Thread-1    ] [INFO ] [django.server       ]  "GET /get_team_players/1/ HTTP/1.1" 200 185
2018-06-26 11:24:54,170 [Thread-3    ] [INFO ] [django.server       ]  "GET /get_team_players/1/ HTTP/1.1" 200 185
2018-06-26 11:25:16,276 [Thread-4    ] [INFO ] [django.server       ]  "GET /get_team_players/2/ HTTP/1.1" 200 70540
2018-06-26 11:25:22,102 [Thread-5    ] [INFO ] [django.server       ]  "GET /get_team_players/3/ HTTP/1.1" 200 98
2018-06-26 11:25:35,663 [Thread-6    ] [INFO ] [django.server       ]  "GET /get_players/ HTTP/1.1" 200 154300
2018-06-26 11:25:40,073 [Thread-7    ] [INFO ] [django.server       ]  "GET /get_players/ HTTP/1.1" 200 154300
2018-06-26 11:26:14,273 [Thread-8    ] [INFO ] [django.server       ]  "GET /get_team_players/1/ HTTP/1.1" 200 185
2018-06-26 11:26:18,315 [Thread-9    ] [INFO ] [django.server       ]  "GET /get_team_players/2/ HTTP/1.1" 200 70540
2018-06-26 11:26:57,862 [Thread-10   ] [INFO ] [django.server       ]  "GET /get_players/1 HTTP/1.1" 200 154300
2018-06-26 11:26:59,878 [Thread-11   ] [INFO ] [django.server       ]  "GET /get_players/1/ HTTP/1.1" 200 154300
2018-06-26 11:27:03,090 [Thread-12   ] [INFO ] [django.server       ]  "GET /get_players/1/ HTTP/1.1" 200 154300
2018-06-26 11:27:34,901 [Thread-13   ] [INFO ] [django.server       ]  "GET /player HTTP/1.1" 301 0
2018-06-26 11:27:36,361 [Thread-14   ] [INFO ] [django.server       ]  "GET /player/ HTTP/1.1" 200 70926
2018-06-26 11:28:00,798 [Thread-15   ] [INFO ] [django.server       ]  "GET /get_team_players/2/ HTTP/1.1" 200 70540
2018-06-26 11:28:13,215 [Thread-16   ] [INFO ] [django.server       ]  "GET /get_players/1/ HTTP/1.1" 200 154300
2018-06-26 11:28:18,546 [Thread-17   ] [INFO ] [django.server       ]  "GET /get_players/ HTTP/1.1" 200 154300
2018-06-26 11:54:01,747 [Thread-1    ] [INFO ] [django.server       ]  "GET /get_team_players/2/ HTTP/1.1" 200 70540
2018-06-26 11:54:44,943 [Thread-1    ] [INFO ] [django.server       ]  "GET /get_players/ HTTP/1.1" 200 154300
2018-06-26 12:09:11,699 [Thread-1    ] [WARNI] [django.request      ]  Not Found: /get_all_match
2018-06-26 12:09:11,700 [Thread-1    ] [WARNI] [django.server       ]  "GET /get_all_match HTTP/1.1" 404 3725
2018-06-26 12:09:13,938 [Thread-3    ] [WARNI] [django.request      ]  Not Found: /get_all_match/
2018-06-26 12:09:13,939 [Thread-3    ] [WARNI] [django.server       ]  "GET /get_all_match/ HTTP/1.1" 404 3728
2018-06-26 13:14:00,361 [Thread-1    ] [INFO ] [django.server       ]  "GET /fake_200_players/ HTTP/1.1" 200 7
2018-06-26 13:16:09,007 [Thread-3    ] [INFO ] [django.server       ]  "GET /get_team_players/2/ HTTP/1.1" 200 84832
2018-06-26 14:36:09,978 [Thread-1    ] [INFO ] [django.server       ]  "GET / HTTP/1.1" 200 5174
2018-06-26 14:36:10,015 [Thread-3    ] [INFO ] [django.server       ]  "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 304 0
2018-06-26 14:36:10,016 [Thread-6    ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
2018-06-26 14:36:10,017 [Thread-5    ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
2018-06-26 14:36:10,018 [Thread-4    ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/jquery-3.3.1.min.js HTTP/1.1" 304 0
2018-06-26 14:36:10,039 [Thread-7    ] [INFO ] [django.server       ]  "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 304 0
2018-06-26 14:36:10,041 [Thread-8    ] [INFO ] [django.server       ]  "GET /static/rest_framework/css/prettify.css HTTP/1.1" 304 0
2018-06-26 14:36:10,042 [Thread-9    ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
2018-06-26 14:36:10,043 [Thread-10   ] [INFO ] [django.server       ]  "GET /static/rest_framework/css/default.css HTTP/1.1" 304 0
2018-06-26 14:36:10,045 [Thread-11   ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
2018-06-26 14:36:10,045 [Thread-12   ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
2018-06-26 14:36:10,216 [Thread-13   ] [INFO ] [django.server       ]  "GET /static/rest_framework/img/grid.png HTTP/1.1" 304 0
2018-06-26 14:36:10,453 [Thread-14   ] [WARNI] [django.request      ]  Not Found: /favicon.ico
2018-06-26 14:36:10,453 [Thread-14   ] [WARNI] [django.server       ]  "GET /favicon.ico HTTP/1.1" 404 3719
2018-06-26 14:36:34,323 [Thread-15   ] [INFO ] [django.server       ]  "GET / HTTP/1.1" 200 5174
2018-06-26 14:39:41,740 [Thread-21   ] [INFO ] [django.server       ]  "GET / HTTP/1.1" 200 5174
2018-06-26 15:27:21,474 [Thread-1    ] [INFO ] [django.server       ]  "GET /get_team_players/2/ HTTP/1.1" 200 84832
2018-06-26 15:31:21,386 [Thread-3    ] [INFO ] [django.server       ]  "GET / HTTP/1.1" 200 5174
2018-06-26 15:33:58,834 [Thread-5    ] [INFO ] [django.server       ]  "GET / HTTP/1.1" 200 5174
2018-06-26 16:02:24,146 [Thread-1    ] [INFO ] [django.server       ]  "GET /get_players/ HTTP/1.1" 200 523438
2018-06-28 11:07:39,143 [Thread-3    ] [INFO ] [django.server       ]  "GET / HTTP/1.1" 200 5174
2018-06-28 11:07:39,319 [Thread-1    ] [INFO ] [django.server       ]  "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 200 121200
2018-06-28 11:07:39,326 [Thread-4    ] [INFO ] [django.server       ]  "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 200 3385
2018-06-28 11:07:39,335 [Thread-5    ] [INFO ] [django.server       ]  "GET /static/rest_framework/css/prettify.css HTTP/1.1" 200 817
2018-06-28 11:07:39,339 [Thread-6    ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/jquery-3.3.1.min.js HTTP/1.1" 200 86927
2018-06-28 11:07:39,341 [Thread-7    ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 200 3597
2018-06-28 11:07:39,345 [Thread-8    ] [INFO ] [django.server       ]  "GET /static/rest_framework/css/default.css HTTP/1.1" 200 1131
2018-06-28 11:07:39,352 [Thread-9    ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 200 37045
2018-06-28 11:07:39,358 [Thread-10   ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/default.js HTTP/1.1" 200 1262
2018-06-28 11:07:39,368 [Thread-11   ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/csrf.js HTTP/1.1" 200 1735
2018-06-28 11:07:39,369 [Thread-12   ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 200 13632
2018-06-28 11:07:39,389 [Thread-13   ] [INFO ] [django.server       ]  "GET /static/rest_framework/img/grid.png HTTP/1.1" 200 1458
2018-06-28 11:07:39,442 [Thread-14   ] [WARNI] [django.request      ]  Not Found: /favicon.ico
2018-06-28 11:07:39,445 [Thread-14   ] [WARNI] [django.server       ]  "GET /favicon.ico HTTP/1.1" 404 3719
2018-06-28 11:07:43,151 [Thread-15   ] [INFO ] [django.server       ]  "GET /player/ HTTP/1.1" 200 239377
2018-06-28 11:08:19,976 [Thread-16   ] [ERROR] [django.request      ]  Internal Server Error: /get_players/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/local/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/local/lib/python3.6/http/client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/local/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/local/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/decorators.py", line 53, in handler
    return func(*args, **kwargs)
  File "/code/player_ms/player_app/views.py", line 33, in get_players
    request.urlopen(MSUrls.team + 'get_player_team/', data=data).read()
  File "/usr/local/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/local/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/local/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.6/urllib/request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/local/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 111] Connection refused>
2018-06-28 11:08:20,191 [Thread-16   ] [ERROR] [django.server       ]  "GET /get_players/ HTTP/1.1" 500 206059
2018-06-28 11:08:20,721 [Thread-17   ] [WARNI] [django.request      ]  Not Found: /favicon.ico
2018-06-28 11:08:20,724 [Thread-17   ] [WARNI] [django.server       ]  "GET /favicon.ico HTTP/1.1" 404 3719
2018-06-28 11:08:27,743 [Thread-22   ] [ERROR] [django.request      ]  Internal Server Error: /get_players/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/local/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/local/lib/python3.6/http/client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/local/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/local/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/decorators.py", line 53, in handler
    return func(*args, **kwargs)
  File "/code/player_ms/player_app/views.py", line 33, in get_players
    request.urlopen(MSUrls.team + 'get_player_team/', data=data).read()
  File "/usr/local/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/local/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/local/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.6/urllib/request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/local/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 111] Connection refused>
2018-06-28 11:08:27,823 [Thread-22   ] [ERROR] [django.server       ]  "GET /get_players/ HTTP/1.1" 500 206059
2018-06-28 11:18:26,412 [Thread-4    ] [INFO ] [django.server       ]  "GET / HTTP/1.1" 200 5174
2018-06-28 11:18:26,436 [Thread-1    ] [INFO ] [django.server       ]  "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 200 3385
2018-06-28 11:18:26,465 [Thread-3    ] [INFO ] [django.server       ]  "GET /static/rest_framework/css/default.css HTTP/1.1" 200 1131
2018-06-28 11:18:26,467 [Thread-5    ] [INFO ] [django.server       ]  "GET /static/rest_framework/css/prettify.css HTTP/1.1" 200 817
2018-06-28 11:18:26,482 [Thread-6    ] [INFO ] [django.server       ]  "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 200 121200
2018-06-28 11:18:26,487 [Thread-7    ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 200 3597
2018-06-28 11:18:26,489 [Thread-8    ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/jquery-3.3.1.min.js HTTP/1.1" 200 86927
2018-06-28 11:18:26,492 [Thread-9    ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 200 37045
2018-06-28 11:18:26,496 [Thread-10   ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/csrf.js HTTP/1.1" 200 1735
2018-06-28 11:18:26,513 [Thread-11   ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/default.js HTTP/1.1" 200 1262
2018-06-28 11:18:26,520 [Thread-12   ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 200 13632
2018-06-28 11:18:26,579 [Thread-13   ] [INFO ] [django.server       ]  "GET /static/rest_framework/img/grid.png HTTP/1.1" 200 1458
2018-06-28 11:22:54,595 [Thread-14   ] [INFO ] [django.server       ]  "GET /fake_200_players/ HTTP/1.1" 200 7
2018-06-28 11:23:00,933 [Thread-16   ] [ERROR] [django.request      ]  Internal Server Error: /get_players/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/local/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/local/lib/python3.6/http/client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/local/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/local/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/decorators.py", line 53, in handler
    return func(*args, **kwargs)
  File "/code/player_ms/player_app/views.py", line 33, in get_players
    request.urlopen(MSUrls.team + 'get_player_team/', data=data).read()
  File "/usr/local/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/local/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/local/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.6/urllib/request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/local/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 111] Connection refused>
2018-06-28 11:23:01,112 [Thread-16   ] [ERROR] [django.server       ]  "GET /get_players/ HTTP/1.1" 500 206059
2018-06-28 11:27:18,391 [Thread-3    ] [INFO ] [django.server       ]  "GET / HTTP/1.1" 200 5174
2018-06-28 11:27:18,427 [Thread-4    ] [INFO ] [django.server       ]  "GET /static/rest_framework/css/prettify.css HTTP/1.1" 304 0
2018-06-28 11:27:18,431 [Thread-1    ] [INFO ] [django.server       ]  "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 304 0
2018-06-28 11:27:18,438 [Thread-6    ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/jquery-3.3.1.min.js HTTP/1.1" 304 0
2018-06-28 11:27:18,441 [Thread-5    ] [INFO ] [django.server       ]  "GET /static/rest_framework/css/default.css HTTP/1.1" 304 0
2018-06-28 11:27:18,446 [Thread-7    ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
2018-06-28 11:27:18,449 [Thread-8    ] [INFO ] [django.server       ]  "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 304 0
2018-06-28 11:27:18,453 [Thread-9    ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
2018-06-28 11:27:18,475 [Thread-10   ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
2018-06-28 11:27:18,484 [Thread-11   ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
2018-06-28 11:27:18,497 [Thread-12   ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
2018-06-28 11:27:18,560 [Thread-13   ] [INFO ] [django.server       ]  "GET /static/rest_framework/img/grid.png HTTP/1.1" 304 0
2018-06-29 17:21:07,392 [Thread-1    ] [INFO ] [django.server       ]  "GET / HTTP/1.1" 200 5174
2018-06-29 17:21:08,728 [Thread-6    ] [INFO ] [django.server       ]  "GET /static/rest_framework/css/prettify.css HTTP/1.1" 304 0
2018-06-29 17:21:08,728 [Thread-3    ] [INFO ] [django.server       ]  "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 304 0
2018-06-29 17:21:08,730 [Thread-5    ] [INFO ] [django.server       ]  "GET /static/rest_framework/css/default.css HTTP/1.1" 304 0
2018-06-29 17:21:08,734 [Thread-4    ] [INFO ] [django.server       ]  "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 304 0
2018-06-29 17:21:08,774 [Thread-7    ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/jquery-3.3.1.min.js HTTP/1.1" 304 0
2018-06-29 17:21:08,778 [Thread-8    ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
2018-06-29 17:21:08,786 [Thread-9    ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
2018-06-29 17:21:08,788 [Thread-11   ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
2018-06-29 17:21:08,789 [Thread-10   ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
2018-06-29 17:21:08,795 [Thread-12   ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
2018-06-29 17:21:09,013 [Thread-13   ] [INFO ] [django.server       ]  "GET /static/rest_framework/img/grid.png HTTP/1.1" 304 0
2018-06-29 17:40:14,212 [Thread-1    ] [INFO ] [django.server       ]  "GET /get_team_players/2/ HTTP/1.1" 200 99124
2018-06-29 17:42:02,649 [Thread-1    ] [INFO ] [django.server       ]  "GET /get_team_players/2/ HTTP/1.1" 200 99124
2018-06-30 10:56:53,327 [Thread-1    ] [INFO ] [django.server       ]  "GET /get_team_players/2/ HTTP/1.1" 200 99124
2018-06-30 10:57:00,791 [Thread-3    ] [INFO ] [django.server       ]  "GET /get_team_players/2/ HTTP/1.1" 200 99124
